#version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  assectra:
    build:
      context: ./bin/${PHPVERSION_ASSECTRA}
    container_name: "${COMPOSE_PROJECT_NAME}${PHPNAME_ASSECTRA}"
    restart: unless-stopped
    tty: true
    networks:
    - docker.network
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT_ASSECTRA}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT_ASSECTRA}:443"
    links:
      - database
    volumes:
      - ${DOCUMENT_ROOT_ASSECTRA}:/var/www/html
      - ${PHP_INI_ASSECTRA-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR_ASSECTRA-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR_ASSECTRA-./logs/apache2}:/var/log/apache2
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT_ASSECTRA}
      
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: "${COMPOSE_PROJECT_NAME}database"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
